import ExifReader from 'exifreader';

async function checkMetadata(imageUrl){
    try{
        const response = await fetch(imageUrl);
        const arrayBuffer = await response.arrayBuffer();
        const tags = ExifReader.load(arrayBuffer);

        const aiKeywords = [
            "midjourney",
            "dall-e",
            "dalle",
            "stable diffusion",
            "comfyui",
            "firefly",
            "adobe firefly",
            "leonardo ai",
            "stability ai",
            "automatic1111",
            "generative ai",
            "generative-ai",
            "ai generated",
            "ai-generated",
            "ai generated image",
            "artificial intelligence",
            "generated by ai",
            "created with ai",
            "negative prompt",
            "cfg scale",
            "clip skip",
            "sampling steps",
            "sampler",
            "seed:",
            "model hash",
            "lora",
            "checkpoint",
            "text-to-image",
            "text to image",
            "img2img",
            "txt2img"
        ];


        const fieldsToCheck = [
            tags['Software']?.description,
            tags['CreatorTool']?.description,
            tags['UserComment']?.description,
            tags['Parameters']?.description,
            tags['History']?.description     
        ];

        for (const field of fieldsToCheck) {
            if (!field) continue;
            
            const text = field.toLowerCase();
            const isAi = aiKeywords.some(function(keyword){text.includes(keyword)});
            
            if (isAi) {
                return { 
                    detected: true, 
                    reason: `Metadata match: ${field}` 
                };
            }
        }

        return {detected:false, reason:"No suspicious activity in metadata"};


    }
    catch(error){
        console.log(error)
    }
}
